<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Publication;

class PublicationSeeder extends Seeder
{
    public function run()
    {
        $publications = [
            // CSE Department Books
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'isbn' => '978-0262033848',
                'publication_year' => 2009,
                'publisher' => 'MIT Press',
                'department' => 'CSE',
                'type' => 'book',
                'total_copies' => 5,
                'available_copies' => 3,
                'shelf_location' => 'A-15',
                'description' => 'Comprehensive introduction to algorithms and data structures with mathematical analysis.',
            ],
            [
                'title' => 'Java: The Complete Reference',
                'author' => 'Herbert Schildt',
                'isbn' => '978-1260440232',
                'publication_year' => 2020,
                'publisher' => 'McGraw-Hill',
                'department' => 'CSE',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 2,
                'shelf_location' => 'A-23',
                'description' => 'Complete guide to Java programming language with examples and best practices.',
            ],
            [
                'title' => 'Database System Concepts',
                'author' => 'Abraham Silberschatz',
                'isbn' => '978-0078022159',
                'publication_year' => 2019,
                'publisher' => 'McGraw-Hill',
                'department' => 'CSE',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 1,
                'shelf_location' => 'A-45',
                'description' => 'Fundamental concepts of database systems including SQL, transactions, and database design.',
            ],
            [
                'title' => 'Computer Networks',
                'author' => 'Andrew S. Tanenbaum',
                'isbn' => '978-0132126953',
                'publication_year' => 2018,
                'publisher' => 'Pearson',
                'department' => 'CSE',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 4,
                'shelf_location' => 'A-67',
                'description' => 'Comprehensive guide to computer networking protocols, architectures, and implementations.',
            ],
            [
                'title' => 'Operating System Concepts',
                'author' => 'Abraham Silberschatz',
                'isbn' => '978-1118063330',
                'publication_year' => 2017,
                'publisher' => 'Wiley',
                'department' => 'CSE',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 2,
                'shelf_location' => 'A-34',
                'description' => 'Essential concepts of operating systems including process management, memory management, and file systems.',
            ],

            // EEE Department Books
            [
                'title' => 'Fundamentals of Electric Circuits',
                'author' => 'Charles Alexander',
                'isbn' => '978-0073380575',
                'publication_year' => 2016,
                'publisher' => 'McGraw-Hill',
                'department' => 'EEE',
                'type' => 'book',
                'total_copies' => 6,
                'available_copies' => 4,
                'shelf_location' => 'B-12',
                'description' => 'Comprehensive introduction to circuit analysis, including AC/DC circuits and network theorems.',
            ],
            [
                'title' => 'Digital Signal Processing',
                'author' => 'John G. Proakis',
                'isbn' => '978-0131873742',
                'publication_year' => 2018,
                'publisher' => 'Pearson',
                'department' => 'EEE',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 3,
                'shelf_location' => 'B-28',
                'description' => 'Advanced concepts in digital signal processing, filters, and transform techniques.',
            ],
            [
                'title' => 'Power Electronics',
                'author' => 'Ned Mohan',
                'isbn' => '978-0471429081',
                'publication_year' => 2017,
                'publisher' => 'Wiley',
                'department' => 'EEE',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 1,
                'shelf_location' => 'B-35',
                'description' => 'Fundamentals of power electronics including converters, inverters, and motor drives.',
            ],
            [
                'title' => 'Microelectronic Circuits',
                'author' => 'Adel S. Sedra',
                'isbn' => '978-0199339136',
                'publication_year' => 2019,
                'publisher' => 'Oxford University Press',
                'department' => 'EEE',
                'type' => 'book',
                'total_copies' => 5,
                'available_copies' => 3,
                'shelf_location' => 'B-41',
                'description' => 'Comprehensive coverage of analog and digital electronic circuits and systems.',
            ],

            // Textile Department Books
            [
                'title' => 'Textile Science',
                'author' => 'Arthur Price',
                'isbn' => '978-1628925135',
                'publication_year' => 2018,
                'publisher' => 'Waveland Press',
                'department' => 'Textile',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 2,
                'shelf_location' => 'C-15',
                'description' => 'Fundamentals of textile fibers, yarns, fabrics, and their properties.',
            ],
            [
                'title' => 'Fabric Manufacturing Technology',
                'author' => 'P. R. Lord',
                'isbn' => '978-1855733695',
                'publication_year' => 2016,
                'publisher' => 'Woodhead Publishing',
                'department' => 'Textile',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 3,
                'shelf_location' => 'C-22',
                'description' => 'Advanced techniques in weaving, knitting, and nonwoven fabric production.',
            ],
            [
                'title' => 'Textile Dyeing and Printing',
                'author' => 'Miles C. Fairhurst',
                'isbn' => '978-1782420385',
                'publication_year' => 2017,
                'publisher' => 'Woodhead Publishing',
                'department' => 'Textile',
                'type' => 'book',
                'total_copies' => 2,
                'available_copies' => 1,
                'shelf_location' => 'C-38',
                'description' => 'Chemical processes and techniques used in textile coloration and printing.',
            ],

            // Architecture Department Books
            [
                'title' => 'A History of Architecture',
                'author' => 'Spiro Kostof',
                'isbn' => '978-0195083781',
                'publication_year' => 2015,
                'publisher' => 'Oxford University Press',
                'department' => 'Arch',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 2,
                'shelf_location' => 'D-11',
                'description' => 'Comprehensive survey of architectural history from ancient to modern times.',
            ],
            [
                'title' => 'Building Construction Illustrated',
                'author' => 'Francis D.K. Ching',
                'isbn' => '978-1118458341',
                'publication_year' => 2019,
                'publisher' => 'Wiley',
                'department' => 'Arch',
                'type' => 'book',
                'total_copies' => 5,
                'available_copies' => 4,
                'shelf_location' => 'D-26',
                'description' => 'Visual guide to building systems, materials, and construction methods.',
            ],
            [
                'title' => 'Urban Design and Planning',
                'author' => 'Kevin Lynch',
                'isbn' => '978-0262620017',
                'publication_year' => 2016,
                'publisher' => 'MIT Press',
                'department' => 'Arch',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 2,
                'shelf_location' => 'D-33',
                'description' => 'Principles of urban design, city planning, and environmental psychology.',
            ],

            // Civil Engineering Department Books
            [
                'title' => 'Structural Analysis',
                'author' => 'Russell C. Hibbeler',
                'isbn' => '978-0134610672',
                'publication_year' => 2018,
                'publisher' => 'Pearson',
                'department' => 'Civil',
                'type' => 'book',
                'total_copies' => 5,
                'available_copies' => 3,
                'shelf_location' => 'E-14',
                'description' => 'Fundamental principles of structural analysis for beams, frames, and trusses.',
            ],
            [
                'title' => 'Soil Mechanics and Foundation Engineering',
                'author' => 'B.C. Punmia',
                'isbn' => '978-8131808290',
                'publication_year' => 2017,
                'publisher' => 'Laxmi Publications',
                'department' => 'Civil',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 2,
                'shelf_location' => 'E-27',
                'description' => 'Comprehensive study of soil properties, bearing capacity, and foundation design.',
            ],
            [
                'title' => 'Concrete Technology',
                'author' => 'M.S. Shetty',
                'isbn' => '978-8121926171',
                'publication_year' => 2016,
                'publisher' => 'S. Chand Publishing',
                'department' => 'Civil',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 1,
                'shelf_location' => 'E-41',
                'description' => 'Properties of concrete, mix design, durability, and quality control.',
            ],

            // MPE Department Books
            [
                'title' => 'Manufacturing Processes',
                'author' => 'Kalpakjian Serope',
                'isbn' => '978-0134290553',
                'publication_year' => 2019,
                'publisher' => 'Pearson',
                'department' => 'MPE',
                'type' => 'book',
                'total_copies' => 4,
                'available_copies' => 3,
                'shelf_location' => 'F-18',
                'description' => 'Comprehensive coverage of manufacturing processes, materials, and quality control.',
            ],
            [
                'title' => 'Thermodynamics: An Engineering Approach',
                'author' => 'Yunus A. Cengel',
                'isbn' => '978-0073398174',
                'publication_year' => 2018,
                'publisher' => 'McGraw-Hill',
                'department' => 'MPE',
                'type' => 'book',
                'total_copies' => 5,
                'available_copies' => 4,
                'shelf_location' => 'F-25',
                'description' => 'Fundamental principles of thermodynamics with engineering applications.',
            ],
            [
                'title' => 'Machine Design',
                'author' => 'Robert L. Norton',
                'isbn' => '978-0133356717',
                'publication_year' => 2017,
                'publisher' => 'Pearson',
                'department' => 'MPE',
                'type' => 'book',
                'total_copies' => 3,
                'available_copies' => 2,
                'shelf_location' => 'F-32',
                'description' => 'Design principles for mechanical components including gears, bearings, and shafts.',
            ],

            // Thesis Examples
            [
                'title' => 'Machine Learning Applications in Network Security',
                'author' => 'Md. Rahman Ahmed',
                'isbn' => null,
                'publication_year' => 2023,
                'publisher' => 'AUST',
                'department' => 'CSE',
                'type' => 'thesis',
                'total_copies' => 1,
                'available_copies' => 1,
                'shelf_location' => 'T-CSE-01',
                'description' => 'Research on applying machine learning algorithms for intrusion detection systems.',
            ],
            [
                'title' => 'Smart Grid Implementation in Bangladesh',
                'author' => 'Fatima Khatun',
                'isbn' => null,
                'publication_year' => 2022,
                'publisher' => 'AUST',
                'department' => 'EEE',
                'type' => 'thesis',
                'total_copies' => 1,
                'available_copies' => 1,
                'shelf_location' => 'T-EEE-03',
                'description' => 'Analysis of smart grid technologies and their potential implementation in Bangladesh.',
            ],
            [
                'title' => 'Sustainable Textile Manufacturing Practices',
                'author' => 'Sarah Johnson',
                'isbn' => null,
                'publication_year' => 2023,
                'publisher' => 'AUST',
                'department' => 'Textile',
                'type' => 'thesis',
                'total_copies' => 1,
                'available_copies' => 1,
                'shelf_location' => 'T-TEX-02',
                'description' => 'Environmental impact assessment of textile manufacturing and sustainable alternatives.',
            ],
            [
                'title' => 'Earthquake Resistant Building Design in Dhaka',
                'author' => 'Mohammad Hassan',
                'isbn' => null,
                'publication_year' => 2022,
                'publisher' => 'AUST',
                'department' => 'Civil',
                'type' => 'thesis',
                'total_copies' => 1,
                'available_copies' => 1,
                'shelf_location' => 'T-CIV-01',
                'description' => 'Seismic analysis and design recommendations for high-rise buildings in Dhaka.',
            ],
        ];

        foreach ($publications as $publication) {
            Publication::create($publication);
        }
    }
}